default:
suites:
  default:
  contexts:
  - FeatureContext
  - Drupal\DrupalExtension\Context\DrupalContext
  - Drupal\DrupalExtension\Context\MinkContext
  - Drupal\DrupalExtension\Context\MessageContext
  - Drupal\DrupalExtension\Context\DrushContext
extensions:
  "Behat\\MinkExtension":
  goutte: null
  base_url: 'https://drupal.ddev.site'
  javascript_session: selenium2
  selenium2:
    browser: "chrome"
    wd_host: http://selenium:4444/wd/hub
    capabilities:
    extra_capabilities:
      idle-timeout: 50
  Drupal\DrupalExtension:
  blackbox: ~
